import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest'
import type { BackendState } from '../../../shared/bridge'
import type { InstallStatus } from '../../types/domain'
import { defaultSettings } from '../../test/fixtures'
import { fixture, running } from '../../test/install-fixtures'

describe('installation connection', () => {
  beforeEach(() => vi.useFakeTimers({ toFake: ['setTimeout', 'clearTimeout', 'performance'] }))
  afterEach(() => vi.useRealTimers())
  it('polls serially 1.2 seconds after completion, never while a read is pending', async () => {
    const f = fixture()
    let finish!: (value: InstallStatus) => void
    f.client.getInstallStatus.mockImplementationOnce(() => new Promise((resolve) => { finish = resolve }))
    f.observer.start()
    await vi.advanceTimersByTimeAsync(1500)
    expect(f.client.getInstallStatus).toHaveBeenCalledTimes(1)
    finish(running)
    await vi.advanceTimersByTimeAsync(1199)
    expect(f.client.getInstallStatus).toHaveBeenCalledTimes(1)
    await vi.advanceTimersByTimeAsync(1)
    expect(f.client.getInstallStatus).toHaveBeenCalledTimes(2)
    f.observer.dispose()
    expect(vi.getTimerCount()).toBe(0)
  })
  it('backs off 1, 2, 4, 8, 8 seconds and reaches the exact monotonic deadline', async () => {
    const f = fixture(), calls: number[] = []
    f.client.getInstallStatus.mockImplementation(async () => { calls.push(performance.now()); throw { code: 'request_timeout' } })
    f.observer.start()
    await vi.advanceTimersByTimeAsync(29_999)
    expect(calls).toEqual([0, 1000, 3000, 7000, 15000, 23000])
    expect(f.changed).toHaveBeenLastCalledWith(expect.objectContaining({ phase: 'reconnecting' }))
    await vi.advanceTimersByTimeAsync(1)
    expect(f.changed).toHaveBeenLastCalledWith({ phase: 'recovery', elapsedMs: 30_000, reason: 'request_timeout' })
    expect(vi.getTimerCount()).toBe(0)
    f.observer.dispose()
  })
  it('bounds silent requests, caps the last request, and ignores every late response', async () => {
    const f = fixture(), resolvers: ((value: InstallStatus) => void)[] = []
    const times: number[] = []
    f.client.getInstallStatus.mockImplementation(() => { times.push(performance.now()); return new Promise((resolve) => resolvers.push(resolve)) })
    f.observer.start()
    await vi.advanceTimersByTimeAsync(31_999)
    expect(times).toEqual([0, 3000, 7000, 13000, 23000])
    expect(f.changed).toHaveBeenLastCalledWith(expect.objectContaining({ phase: 'reconnecting' }))
    await vi.advanceTimersByTimeAsync(1)
    expect(f.changed).toHaveBeenLastCalledWith(expect.objectContaining({ phase: 'recovery', elapsedMs: 30_000 }))
    for (const resolve of resolvers) resolve({ ...running, status: 'completed' })
    await vi.advanceTimersByTimeAsync(10_000)
    expect(f.received).not.toHaveBeenCalled()
    f.observer.dispose()
  })
  it('caps an in-flight final read to the remaining second', async () => {
    const f = fixture()
    f.client.getInstallStatus.mockRejectedValueOnce({ code: 'request_timeout' })
      .mockImplementationOnce(() => new Promise(() => {}))
      .mockImplementationOnce(() => new Promise(() => {}))
      .mockImplementationOnce(() => new Promise(() => {}))
      .mockRejectedValueOnce({ code: 'request_timeout' })
      .mockImplementationOnce(() => new Promise(() => {}))
    f.observer.start()
    await vi.advanceTimersByTimeAsync(29_000)
    expect(f.client.getInstallStatus).toHaveBeenLastCalledWith('one', 1000, 1)
    await vi.advanceTimersByTimeAsync(999)
    expect(f.changed).toHaveBeenLastCalledWith(expect.objectContaining({ phase: 'reconnecting' }))
    await vi.advanceTimersByTimeAsync(1)
    expect(f.changed).toHaveBeenLastCalledWith(expect.objectContaining({ phase: 'recovery', elapsedMs: 30_000 }))
    f.observer.dispose()
  })
  it('shows a known exit immediately without starting a status request', async () => {
    const f = fixture()
    f.client.getBackendState.mockResolvedValue({ generation: 1, status: 'exited' })
    f.observer.start()
    await vi.advanceTimersByTimeAsync(0)
    expect(f.changed).toHaveBeenLastCalledWith(expect.objectContaining({ phase: 'recovery', reason: 'backend_exited' }))
    expect(f.client.getInstallStatus).not.toHaveBeenCalled()
    f.observer.dispose()
  })
  it('recovers actual status without replay and stops at settings resolution', async () => {
    const f = fixture()
    f.client.getInstallStatus.mockRejectedValueOnce({ code: 'request_timeout' })
    f.observer.start()
    await vi.advanceTimersByTimeAsync(1000)
    expect(f.received).toHaveBeenCalledWith(running)
    expect(f.changed).toHaveBeenLastCalledWith({ phase: 'connected', elapsedMs: 0 })
    f.client.getInstallStatus.mockResolvedValue({ ...running, status: 'awaiting_resolution', verified_values: {}, resolution: { status: 'conflict', snapshot: { revision: 'r', settings: defaultSettings }, conflicts: [] } } as InstallStatus)
    await vi.advanceTimersByTimeAsync(1200)
    expect(vi.getTimerCount()).toBe(0)
    f.event({ generation: 1, status: 'exited' })
    expect(f.changed).toHaveBeenLastCalledWith(expect.objectContaining({ phase: 'recovery', reason: 'backend_exited' }))
    f.observer.dispose()
    expect(f.unsubscribe).toHaveBeenCalledOnce()
  })
  it.each([{ generation: 1, status: 'exited' }, { generation: 2, status: 'running' }] as BackendState[])('ignores in-flight replies after backend change %j', async (event) => {
    const f = fixture()
    let finish!: (value: InstallStatus) => void
    f.client.getInstallStatus.mockImplementation(() => new Promise((resolve) => { finish = resolve }))
    f.observer.start(); await vi.advanceTimersByTimeAsync(0)
    f.event(event)
    expect(f.changed).toHaveBeenLastCalledWith(expect.objectContaining({ phase: 'recovery', elapsedMs: 0 }))
    finish(running); await vi.advanceTimersByTimeAsync(0)
    expect(f.received).not.toHaveBeenCalled()
    f.observer.dispose()
  })
  it('rejects the wrong operation and malformed status immediately', async () => {
    const f = fixture()
    f.client.getInstallStatus.mockResolvedValue({ ...running, install_id: 'old' })
    f.observer.start(); await vi.advanceTimersByTimeAsync(0)
    expect(f.changed).toHaveBeenLastCalledWith(expect.objectContaining({ phase: 'recovery', reason: 'protocol_error' }))
    expect(f.received).not.toHaveBeenCalled()
    f.observer.dispose()
  })
  it('cleans up on disposal and ignores an outstanding response', async () => {
    const f = fixture()
    let finish!: (value: InstallStatus) => void
    f.client.getInstallStatus.mockImplementation(() => new Promise((resolve) => { finish = resolve }))
    f.observer.start(); await vi.advanceTimersByTimeAsync(0)
    f.observer.dispose(); finish(running); await vi.advanceTimersByTimeAsync(60_000)
    expect(f.received).not.toHaveBeenCalled()
    expect(f.unsubscribe).toHaveBeenCalledOnce()
    expect(vi.getTimerCount()).toBe(0)
  })
})
