"""Runtime discovery and filesystem support."""

from .environment import (
    ENCODER_PREFERENCE,
    REQUIRED_WHISPER_MODEL,
    WhisperDeviceStatus,
    available_encoders,
    ensure_executable_directory_on_path,
    find_ffmpeg,
    find_ffprobe,
    format_bytes,
    get_calibrated_transcription_factor,
    get_cuda_memory_mib,
    get_directory_size,
    get_external_whisper_cache_dir,
    get_profanity_censor_words_file,
    get_profanity_exclusions_file,
    get_whisper_cache_dir,
    get_whisper_device_status,
    get_whisper_profile_key,
    get_whisper_timing_history_path,
    load_profanity_censor_words,
    load_profanity_exclusions,
    load_word_list,
    read_project_config,
    record_transcription_timing,
    require_whisper_model,
    select_video_encoder,
    select_working_video_encoder,
    video_encoder_runtime_available,
)
from .paths import PROJECT_ROOT, RuntimePaths, get_project_root, get_runtime_paths

__all__ = [
    "ENCODER_PREFERENCE",
    "PROJECT_ROOT",
    "REQUIRED_WHISPER_MODEL",
    "RuntimePaths",
    "WhisperDeviceStatus",
    "available_encoders",
    "ensure_executable_directory_on_path",
    "find_ffmpeg",
    "find_ffprobe",
    "format_bytes",
    "get_calibrated_transcription_factor",
    "get_cuda_memory_mib",
    "get_directory_size",
    "get_external_whisper_cache_dir",
    "get_profanity_censor_words_file",
    "get_profanity_exclusions_file",
    "get_project_root",
    "get_runtime_paths",
    "get_whisper_cache_dir",
    "get_whisper_device_status",
    "get_whisper_profile_key",
    "get_whisper_timing_history_path",
    "load_profanity_censor_words",
    "load_profanity_exclusions",
    "load_word_list",
    "read_project_config",
    "record_transcription_timing",
    "require_whisper_model",
    "select_video_encoder",
    "select_working_video_encoder",
    "video_encoder_runtime_available",
]